config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root 'home#index'
  get 'about' => 'about#index'
  get 'resources' => 'resources#index'
  get 'contact' => 'contact#index'
#  get 'letter' => 'letter#index'
  get 'advertising' => 'advertising#index'
  get 'success' => 'success#index'

  get "/login/:token" => "memberships#login"
  get "/logout" => "memberships#logout"

  delete "/memberships/:id" => "memberships#destroy"


  resources :memberships do |memberships|
    resources :charges
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/charge.rb
class Charge < ApplicationRecord
  belongs_to :membership
  belongs_to :membership_type

  def pluralize
    unless membership_type.duration.to_i / 12 < 1.1
      "s"
    end
  end

  def last_paid_time
    created_at - 4.hours
  end

  def price_cdn
    "#{membership_type.price / 100}.00 CDN"
  end

  def duration_name
    "#{membership_type.duration.to_i / 12} year#{pluralize} - #{membership_type.name}"
  end



end

app/models/membership.rb
class Membership < ApplicationRecord
  belongs_to :membership_type
  has_many :charges
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true
  validates :address, presence: true
  validates :city, presence: true
  validates :province, presence: true
  validates :postal, presence: true
  validates :phone, presence: true
  validates :membership_type_id, presence: true
  #validates :token, unique: true

  before_create :generate_token

  def last_paid_time
    created_at - 4.hours
  end
  def next_paid_time
    if membership_type.duration.to_i / 12 < 1.1
      last_paid_time + 365.days
    else
      last_paid_time + 730.days
    end
  end
  def mailing_list
    email_communications == "true"
  end

  def generate_token
    self.token ||= loop do
      random_token = SecureRandom.urlsafe_base64(nil, false)
      break random_token unless Membership.exists?(token: random_token)
    end
  end

end

app/models/membership_type.rb
class MembershipType < ApplicationRecord
  has_many :memberships
  def pluralize
    unless duration.to_i / 12 < 1.1
      "s"
    end
  end
  def display_name
    "#{name} - #{duration.to_i / 12} year#{pluralize}"
  end

  def display_name_long
    "#{name} Membership - #{duration.to_i / 12} year#{pluralize}"
  end

  def display_name_price_cdn
    "#{name} - #{duration.to_i / 12} year#{pluralize} - #{price / 100}.00 CDN"
  end

  def duration_years
    "#{duration.to_i / 12}"
  end

  def price_cdn
    "#{price / 100}.00 CDN"
  end

  def price_dollar
    "#{price / 100}.00"
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable

end

app/controllers/about_controller.rb
class AboutController < ApplicationController
#  before_filter :redirect_to_https
  def index
  end
end

app/controllers/advertising_controller.rb
class AdvertisingController < ApplicationController
#  before_filter :redirect_to_https
  def index
  end
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
#  before_filter :redirect_to_https
  before_filter :load_membership
  before_filter :login_from_session!
  before_filter :ensure_authenticated!

def new
  if @membership.nil?
    flash[:error] = "membership not found"
    redirect_to "/"
  end
  @membership_type = @membership.membership_type
end

def index
end

def show
  @charge = @membership.charges.find(params[:id])
end

def create
  # Amount in cents
  @membership_type = @membership.membership_type
  @stripe_token = params[:stripe_token]

  customer = Stripe::Customer.create(
    :email => params[:stripeEmail],
    :source  => params[:stripeToken]
  )

  stripecharge = Stripe::Charge.create(
    :customer    => customer.id,
    :amount      => @membership_type.price,
    :description => "Charge - #{@membership.first_name} #{@membership.last_name}",
    :currency    => 'cad'
  )

  if stripecharge["paid"] == true
    charge = Charge.create({
      membership: @membership,
      membership_type: @membership_type,
      stripe_token: @stripe_token,
      charge_id: stripecharge.id,
      customer_id: customer.id

    })

    if charge.errors.empty?
      redirect_to "/success"
      NewMembershipMailer.welcome_email(@membership).deliver_now
      NewMembershipMailer.welcome_email_admin(@membership).deliver_now
    else
      redirect_to "/memberships/#{@membership.id}/charges/new"
      flash[:error] = "There was a problem creating your account. Please check all fields and try again."
    end
  end


  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to "/memberships/#{@membership.id}/charges/new"
  end
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
#  before_filter :redirect_to_https
  def index
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
#  before_filter :redirect_to_https
  def index
  end
end

app/controllers/letter_controller.rb
class LetterController < ApplicationController
#  before_filter :redirect_to_https
  def index
  end
end

app/controllers/memberships_controller.rb
class MembershipsController < ApplicationController
  before_action :authenticate_user!, :except => [:index, :new, :edit, :login, :create, :destroy]
#  before_filter :redirect_to_https
  before_filter :load_membership, only: [:show, :edit, :update, :destroy]
  before_filter :login_from_session!, except: [:index, :new, :login, :create, :destroy]
  before_filter :ensure_authenticated!, except: [:index, :new, :login, :create]

  def index
    @memberships = Membership.all
    if current_user.nil?
      redirect_to "/memberships/new"
    end
  end
  def new
    @membership_types = MembershipType.all
  end
  def edit
    @membership_types = MembershipType.all
  end
  def show
    #redirect_to "/" unless @membership == @current_membership
    @membership
  end
  def create
    puts params
    params[:memberships].permit!
    @membership = Membership.create(params[:memberships])
    if @membership.errors.empty?
      session[:membership_id] = @membership.id
      redirect_to "/memberships/#{@membership.id}/charges/new"
    else
      redirect_to "/memberships/new"
      flash[:error] = "There was a problem creating your membership. Please check all fields and try again."
    end
  end
  def update
    params[:memberships].permit!
    @membership.update_attributes(params[:memberships])
    if @membership.errors.empty?
      redirect_to "/memberships/#{@membership.id}/charges/new"
    else
      redirect_to "/memberships/new"
      flash[:error] = "There was a problem creating your membership. Please check all fields and try again."
    end
  end

  def login
    @membership = Membership.where(token: params[:token]).first
    if @membership
      session[:membership_id] = @membership.id
      redirect_to "/memberships/#{@membership.id}"
    else
      redirect_to "/"
    end
  end

  def destroy
    @membership = Membership.find(params[:id])
    @charges = @membership.charges.find(params[:id])
    @membership.destroy
    redirect_to "/memberships"
    flash[:notice] = "Membership successfully deleted."
  end

  def logout
    session[:membership_id] = nil
    flash[:info] = "logged out"
    redirect_to "/"
  end

end

app/controllers/resources_controller.rb
class ResourcesController < ApplicationController
#  before_filter :redirect_to_https
  def index
  end
end

app/controllers/success_controller.rb
class SuccessController < ApplicationController
#  before_filter :redirect_to_https
  def index
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/advertising_helper.rb
module AdvertisingHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/letter_helper.rb
module LetterHelper
end

app/helpers/membership_helper.rb
module MembershipHelper
end

app/helpers/resources_helper.rb
module ResourcesHelper
end

app/helpers/success_helper.rb
module SuccessHelper
end

app/views/memberships/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-12 col-lg-12 no_pad" style="border-left:1px solid #e6e6e6; border-right:0px solid #e6e6e6;">
      <div class="section_top_img">
        <img src="/assets/mem_top_img.jpg" class="img-responsive">
      </div>
    </div>
  </div>
</div>

<div class="container container_style">
  <div class="row" style="margin-top:40px;">
    <div class="col-sm-12 col-md-12 col-lg-12 no_pad">
      <% if @current_user.nil? %>
        <div class="about_head">
          Edit your <span>Membership Details</span>
        </div>
        <div class="about_body">
          Edit your EMLPO membership details using the form below. Then click submit to return to the payment page.
        </div>
      <% else %>
        <div class="about_head">
          Edit <span>Membership Details</span>
        </div>
        <div class="about_body">
          Edit the membership details for <%= @membership.first_name %> <%= @membership.first_name %> using the form below and click 'Save Changes'.
        </div>
      <% end %>
    </div>
  </div>
  <div class="row" style="margin-top:16px;">
    <div class="col-sm-12 col-md-12 col-lg-12 no_pad">
      <div class="">
        <div class="mem_col_head_shell online">
          Membership <span>Details</span>
          <div class="mem_col_head_req">* Required</div>
        </div>
        <%= form_for :memberships, url: memberships_path(@membership) do |f| %>

          <div class="mem_form_line_left">
            <%= f.label :first_name %> *<br>
            <%= f.text_field :first_name, :value => @membership.first_name %>
          </div>
          <div class="mem_form_line_right">
            <%= f.label :last_name %> *<br>
            <%= f.text_field :last_name, :value => @membership.last_name %>
          </div>
          <div class="clearfix"></div>


          <div class="mem_form_line_left">
            <%= f.label :email_Address %> *<br>
            <%= f.email_field :email, :value => @membership.email %>
          </div>
          <div class="mem_form_line_right">
            <%= f.label :company_name %><br>
            <%= f.text_field :company_name, :value => @membership.company_name %>
          </div>
          <div class="clearfix"></div>
          <div style="width:100%; margin:15px 0 30px 0; border-top:1px dashed #e6e6e6;"></div>

          <div class="mem_form_line_full">
            <%= f.label :address %> *<br>
            <%= f.text_field :address, :value => @membership.address %>
          </div>

          <div class="mem_form_line_left">
            <%= f.label :city %> *<br>
            <%= f.text_field :city, :value => @membership.city %>
          </div>
          <div class="mem_form_line_right">
            <%= f.label :province %> *<br>
            <%= f.text_field :province, :value => @membership.province %>
          </div>
          <div class="clearfix"></div>

          <div class="mem_form_line_left">
              <%= f.label :postal %> *<br>
              <%= f.text_field :postal, :value => @membership.postal %>
          </div>
          <div class="mem_form_line_right">
            <%= f.label :phone_number %> *<br>
            <%= f.text_field :phone, :value => @membership.phone %>
          </div>
          <div class="clearfix"></div>

          <div class="mem_form_line_full">
            <%= f.label :notes %><br>
            <%= f.text_area :notes, :value => @membership.notes %>
          </div>

          <div class="mem_form_line_full">
            <%= f.label :membership_type_id %> *<br>
            <%= f.select(:membership_type_id) do %>
              <% @membership_types.each do |membership_type| -%>
                <%= content_tag(:option, membership_type.display_name_price_cdn, value: membership_type.id) %>
              <% end %>
            <% end %>
          </div>
          <div style="width:100%; margin:15px 0 30px 0; border-top:1px dashed #e6e6e6;"></div>

          <% if @current_user.nil? %>
            <div class="mem_form_line_full">
              <%= f.submit "Continue and Pay", class: "mem_form_btn"%>
            </div>
          <% else %>
          <div class="mem_form_line_full">
            <%= f.submit "Save Changes", class: "mem_form_btn"%>
            <button type="button" class="mem_form_cancel_btn" data-toggle="modal" data-target="#confirm_delete_modal">
              Delete Membership
            </button>

          </div>
          <% end %>


        <% end %>
      </div>
    </div>

    </div>
  </div>
</div>


<div class="bot_tag_shell">
  <div class="container">
    <div class="row">
      <div class="col-sm-12 col-md-12 col-lg-12 no_pad">
        <div class="bot_tag_head"><span>Contact us</span> to learn more <br class="visible-xs">about EMLPO <br class="hidden-xs">and what <br class="visible-xs">a membership has <br class="visible-xs">to offer.</div>
        <a href="#"><div class="bot_tag_btn">Contact EMLPO</div></a>
      </div>
    </div>
  </div>
</div>

app/views/memberships/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-12 col-lg-12 no_pad" style="border-left:1px solid #e6e6e6; border-right:0px solid #e6e6e6;">
      <div class="section_top_img">
        <img src="/assets/mem_top_img.jpg" class="img-responsive">
      </div>
    </div>
  </div>
</div>

<div class="container container_style">
  <div class="row" style="margin-top:40px;">
    <div class="col-sm-12 col-md-12 col-lg-12 no_pad">
      <div class="about_head">
        All <span>EMLPO Memberships</span>
      </div>

    </div>
  </div>
  <div class="row" style="margin-top:0px;">
    <div class="col-sm-12 col-md-12 col-lg-12 no_pad">
      <% if @memberships.nil? %>
        <div class="mem_empty">New member signups along with related charges will appear here.</div>
      <% else %>
        <div class="con_table_shell">
          <div class="table-responsive" style="border:0 !important;">
            <table class="table">
              <thead>
                <tr class="tr_head">
                  <td>Name</td>
                  <td>Phone Number</td>
                  <td>Email Address</td>
                  <td>Payments</td>
                  <td>Next Payment Due</td>
                  <td></td>
                </tr>
              </thead>
              <tbody>
              <% @memberships.sort_by{ |t| t.next_paid_time }.each do |membership| %>
                <tr class="tr_body">
                  <td class="td_member_1"><%= membership.first_name %> <%= membership.last_name %></td>
                  <td class="td_member_2"><%= membership.phone %></td>
                  <td class="td_member_3"><%= membership.email %></td>
                  <td class="td_member_4"><%= membership.charges.count %></td>
                  <td class="td_member_5"><%= membership.next_paid_time.strftime("%B %e, %Y") %></td>
                  <td class="td_member_6"><a href="/memberships/<%= membership.id %>/edit">Edit</a><a href="/memberships/<%= membership.id %>">View</a></td>
                </tr>
              <% end %>


              </tbody>
            </table>
          </div>
        </div>
        <% end %>
      <div class="about_head">
        Email <span>Communications</span>
      </div>

      <% if @memberships.nil? %>
        <div class="mem_empty">Members that wish to receive email communications will show up here.</div>

      <% else %>
      <div class="con_table_shell">
        <div class="table-responsive" style="border:0 !important;">
          <table class="table">
            <thead>
              <tr class="tr_head">
                <td>Name</td>
                <td>Email Address</td>
                <td></td>

              </tr>
            </thead>
            <tbody>
            <% @memberships.select{ |t| t.email_communications }.each do |membership| %>
              <tr class="tr_body">
                <td class="td_con_email_1"><%= membership.first_name %> <%= membership.last_name %></td>
                <td class="td_con_email_2"><%= membership.email %></td>
                <td class="td_con_email_3"><a href="/memberships/<%= membership.id %>/edit">Edit</a><a href="/memberships/<%= membership.id %>">View</a></td>

              </tr>
            <% end %>


            </tbody>
          </table>
        </div>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/memberships/list.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-12 col-lg-12 no_pad" style="border-left:1px solid #e6e6e6; border-right:0px solid #e6e6e6;">
      <div class="section_top_img">
        <img src="/assets/mem_top_img.jpg" class="img-responsive">
      </div>
    </div>
  </div>
</div>

<div class="container container_style">
  <div class="row" style="margin-top:40px;">
    <div class="col-sm-12 col-md-12 col-lg-12 no_pad">
      <div class="about_head">
        EMLPO <span>Membership</span>
      </div>

    </div>
  </div>
  <div class="row" style="margin-top:0px;">
    <div class="col-sm-12 col-md-12 col-lg-12 no_pad">
      <div class="mem_show_grey">
        <div class="mem_show_line">
          First Name: <span><%= @membership.first_name %></span>
        </div>
        <div class="mem_show_line">
          Last Name: <span><%= @membership.last_name %></span>
        </div>
        <div class="mem_show_line">
          Company Name: <span><%= @membership.company_name %></span>
        </div>
        <div class="mem_show_line">
          Email Address: <span><%= @membership.email %></span>
        </div>
        <div class="mem_show_line">
          Mailing Address: <span><%= @membership.address %></span>
        </div>
        <div class="mem_show_line">
          City: <span><%= @membership.city %></span>
        </div>
        <div class="mem_show_line">
          Province: <span><%= @membership.province %></span>
        </div>
        <div class="mem_show_line">
          Postal Code: <span><%= @membership.postal %></span>
        </div>
        <div class="mem_show_line">
          Phone Number: <span><%= @membership.phone %></span>
        </div>
        <div class="mem_show_line">
          Notes: <span><%= @membership.notes %></span>
        </div>
        <div class="mem_show_line">
          Last Paid: <span><%= @membership.last_paid_time.strftime("%B %e, %Y at %I:%M %p") %></span>
        </div>
        <div class="mem_show_line">
          Next Payment Due: <span><%= @membership.next_paid_time.strftime("%B %e, %Y at %I:%M %p") %></span>
        </div>
        <div class="mem_show_line" style="margin-bottom:30px;">
          Email Communications: <span><%= @membership.email_communications_yesno %></span>
        </div>
        <div class="mem_show_line">
          Membership Type: <span><%= @membership.membership_type.name %></span>
        </div>
        <div class="mem_show_line">
          Membership Type: <span><%= @membership.membership_type.duration_years %> year(s)</span>
        </div>
        <div class="mem_show_line">
          Membership Type: <span>$<%= @membership.membership_type.price_cdn %></span>
        </div>
    </div>
    </div>
  </div>

</div>

<div class="bot_tag_shell">
  <div class="container">
    <div class="row">
      <div class="col-sm-12 col-md-12 col-lg-12 no_pad">
        <div class="bot_tag_head">To receive the benefits <br class="visible-xs">of an EMLPO <br class="hidden-xs">membership, <br class="visible-xs"><span>sign up today!</span></div>
        <a href="#"><div class="bot_tag_btn">Click here to sign up</div></a>
      </div>
    </div>
  </div>
</div>

app/views/memberships/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-12 col-lg-12 no_pad" style="border-left:1px solid #e6e6e6; border-right:0px solid #e6e6e6;">
      <div class="section_top_img">
        <img src="/assets/mem_top_img.jpg" class="img-responsive">
      </div>
    </div>
  </div>
</div>

<div class="container container_style">
  <div class="row" style="margin-top:40px;">
    <div class="col-sm-12 col-md-12 col-lg-12 no_pad">
      <div class="about_head">
        EMLPO <span>Membership</span>
      </div>
      <div class="about_body">
        Thank you for choosing to support the EMLPO with your membership. You can register and pay online below or use the downloadable PDF form to register by mail.
      </div>
    </div>
  </div>
  <div class="row" style="margin-top:16px;">
    <div class="col-sm-12 col-md-8 col-lg-9 no_pad">
      <div class="mem_left_shell">
        <div class="mem_col_head_shell online">
          Register <span>Online</span>
          <div class="mem_col_head_req">* Required</div>
        </div>
        <%= form_for :memberships, :url => memberships_path do |f| %>
          <%= f.text_field :last_paid, value: Time.now.utc - 4.hours, type: "hidden" %>
          <%= f.text_field :next_payment, value: Time.now.utc + 365.days - 4.hours, type: "hidden" %>
          <div class="mem_form_line_left">
            <%= f.label :first_name %> *<br>
            <%= f.text_field :first_name %>
          </div>
          <div class="mem_form_line_right">
            <%= f.label :last_name %> *<br>
            <%= f.text_field :last_name %>
          </div>
          <div class="clearfix"></div>


          <div class="mem_form_line_left">
            <%= f.label :email_Address %> *<br>
            <%= f.email_field :email %>
          </div>
          <div class="mem_form_line_right">
            <%= f.label :company_name %><br>
            <%= f.text_field :company_name %>
          </div>
          <div class="clearfix"></div>
          <div style="width:100%; margin:15px 0 30px 0; border-top:1px dashed #e6e6e6;"></div>

          <div class="mem_form_line_full">
            <%= f.label :address %> *<br>
            <%= f.text_field :address %>
          </div>

          <div class="mem_form_line_left">
            <%= f.label :city %> *<br>
            <%= f.text_field :city %>
          </div>
          <div class="mem_form_line_right">
            <%= f.label :province %> *<br>
            <%= f.text_field :province %>
          </div>
          <div class="clearfix"></div>

          <div class="mem_form_line_left">
              <%= f.label :postal %> *<br>
              <%= f.text_field :postal %>
          </div>
          <div class="mem_form_line_right">
            <%= f.label :phone_number %> *<br>
            <%= f.text_field :phone %>
          </div>
          <div class="clearfix"></div>

          <div class="mem_form_line_full">
            <%= f.label :notes %><br>
            <%= f.text_area :notes %>
          </div>

          <div class="mem_form_line_full">
            <%= f.label :membership_type_id %> *<br>
            <%= f.select(:membership_type_id) do %>
              <% @membership_types.each do |membership_type| -%>
                <%= content_tag(:option, membership_type.display_name_price_cdn, value: membership_type.id) %>
              <% end %>
            <% end %>
          </div>
          <div style="width:100%; margin:15px 0 30px 0; border-top:1px dashed #e6e6e6;"></div>

          <div class="mem_form_line_full">
            <%= f.check_box :email_communications, id: "email_communications", style: "margin-right:10px;" %>
				 		<%= f.label :email_communications, "Yes, I would like to receive emails from EMLPO regarding lake matters" %>

          </div>
          <div class="mem_form_line_full">
            <%= f.submit "Continue and Pay", class: "mem_form_btn"%>
          </div>
        <% end %>
      </div>
    </div>
    <div class="col-sm-12 col-md-4 col-lg-3 no_pad">
      <div class="mem_right_shell">
        <div style="width:100%; margin:15px 0 30px 0; border-top:4px solid #e6e6e6;" class="visible-sm visible-xs"></div>
        <div class="mem_col_head_shell mail">
          Register <span>By Mail</span>
        </div>
        <div class="mem_col_right_num">1</div>
        <div class="mem_col_right_body">Download, print and fill out the registration form PDF</div>
        <a href="/pdf/EMLPO_Membership_Form.pdf" target="_blank"><div class="mem_col_right_btn">Download</div></a>
        <div class="mem_col_right_num">2</div>
        <div class="mem_col_right_body">Send your payment and completed registration form to:</div>
        <div class="mem_col_right_body"><span>Eagle Moose Lake Property Owners Association (EMLPO)</span></div>
        <div class="mem_col_right_address">1048 Elk Drive<br>
Eagle Lake, 0N<br>
K0M 1M0</div>
        <div class="mem_col_right_img">
          <img src="/assets/mem_sidebar_2.jpg" class="img-responsive hidden-sm hidden-xs"></div>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="bot_tag_shell">
  <div class="container">
    <div class="row">
      <div class="col-sm-12 col-md-12 col-lg-12 no_pad">
        <div class="bot_tag_head"><span>Contact us</span> to learn more <br class="visible-xs">about EMLPO <br class="hidden-xs">and what <br class="visible-xs">a membership has <br class="visible-xs">to offer.</div>
        <a href="/contact"><div class="bot_tag_btn">Contact EMLPO</div></a>
      </div>
    </div>
  </div>
</div>

app/views/memberships/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-12 col-lg-12 no_pad" style="border-left:1px solid #e6e6e6; border-right:0px solid #e6e6e6;">
      <div class="section_top_img">
        <img src="/assets/mem_top_img.jpg" class="img-responsive">
      </div>
    </div>
  </div>
</div>

<div class="container container_style">
  <div class="row" style="margin-top:40px;">
    <div class="col-sm-12 col-md-12 col-lg-12 no_pad">
      <div class="about_head">
        EMLPO Membership for <span><%= @membership.first_name %> <%= @membership.last_name %></span>
      </div>

    </div>
  </div>
  <div class="row" style="margin-top:0px;">
    <div class="col-sm-12 col-md-12 col-lg-12 no_pad">
      <div class="mem_show_grey">
        <div class="mem_show_line">
          First Name: <span><%= @membership.first_name %></span>
        </div>
        <div class="mem_show_line">
          Last Name: <span><%= @membership.last_name %></span>
        </div>
        <div class="mem_show_line">
          Company Name: <span><%= @membership.company_name %></span>
        </div>
        <div class="mem_show_line">
          Email Address: <span><%= @membership.email %></span>
        </div>
        <div class="mem_show_line">
          Mailing Address: <span><%= @membership.address %></span>
        </div>
        <div class="mem_show_line">
          City: <span><%= @membership.city %></span>
        </div>
        <div class="mem_show_line">
          Province: <span><%= @membership.province %></span>
        </div>
        <div class="mem_show_line">
          Postal Code: <span><%= @membership.postal %></span>
        </div>
        <div class="mem_show_line">
          Phone Number: <span><%= @membership.phone %></span>
        </div>
        <div class="mem_show_line">
          Notes: <span><%= @membership.notes %></span>
        </div>
        <div class="mem_show_line">
          Last Paid: <span><%= @membership.last_paid_time.strftime("%B %e, %Y at %I:%M %p") %></span>
        </div>
        <div class="mem_show_line">
          Next Payment Due: <span><%= @membership.next_paid_time.strftime("%B %e, %Y at %I:%M %p") %></span>
        </div>
        <div class="mem_show_line" style="margin-bottom:30px;">
          Email Communications: <span><%= @membership.email_communications %></span>
        </div>
        <div class="mem_show_line">
          Membership Type: <span><%= @membership.membership_type.name %></span>
        </div>
        <div class="mem_show_line">
          Membership Type: <span><%= @membership.membership_type.duration_years %> year<%= @membership.membership_type.pluralize %></span>
        </div>
        <div class="mem_show_line">
          Membership Type: <span>$<%= @membership.membership_type.price_cdn %></span>
        </div>
    </div>
  </div>
</div>
<div class="row" style="margin-top:40px;">
  <div class="col-sm-12 col-md-12 col-lg-12 no_pad">
    <div class="about_head">
      Charges for <span><%= @membership.first_name %> <%= @membership.last_name %></span>
    </div>

  </div>
</div>
<div class="row" style="margin-top:0px;">
  <div class="col-sm-12 col-md-12 col-lg-12 no_pad">
    <% @membership.charges.each do |charge| %>
      <div class="mem_show_grey" style="margin-bottom:20px;">
        <div class="mem_show_line">
          Payment Made: <span><%= charge.last_paid_time.strftime("%B %e, %Y at %I:%M %p") %></span>
        </div>
        <div class="mem_show_line">
          Amount: <span><%= charge.price_cdn %></span>
        </div>
        <div class="mem_show_line">
          Type: <span><%= charge.duration_name %></span>
        </div>
        <div class="mem_show_line">
          Stripe Charge ID: <span><%= charge.charge_id %></span>
        </div>
        <div class="mem_show_line">
          Stripe Customer ID: <span><%= charge.customer_id %></span>

        </div>
      </div>
    <% end %>
    </div>
  </div>

</div>