config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root 'home#index'
  get 'about' => 'about#index'
  get 'resources' => 'resources#index'
  get 'contact' => 'contact#index'
#  get 'letter' => 'letter#index'
  get 'advertising' => 'advertising#index'
  get 'success' => 'success#index'

  get "/login/:token" => "memberships#login"
  get "/logout" => "memberships#logout"

  delete "/memberships/:id" => "memberships#destroy"


  resources :memberships do |memberships|
    resources :charges
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/charge.rb
class Charge < ApplicationRecord
  belongs_to :membership
  belongs_to :membership_type

  def pluralize
    unless membership_type.duration.to_i / 12 < 1.1
      "s"
    end
  end

  def last_paid_time
    created_at - 4.hours
  end

  def price_cdn
    "#{membership_type.price / 100}.00 CDN"
  end

  def duration_name
    "#{membership_type.duration.to_i / 12} year#{pluralize} - #{membership_type.name}"
  end



end

app/models/membership.rb
class Membership < ApplicationRecord
  belongs_to :membership_type
  has_many :charges
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true
  validates :address, presence: true
  validates :city, presence: true
  validates :province, presence: true
  validates :postal, presence: true
  validates :phone, presence: true
  validates :membership_type_id, presence: true
  #validates :token, unique: true

  before_create :generate_token

  def last_paid_time
    created_at - 4.hours
  end
  def next_paid_time
    if membership_type.duration.to_i / 12 < 1.1
      last_paid_time + 365.days
    else
      last_paid_time + 730.days
    end
  end
  def mailing_list
    email_communications == "true"
  end

  def generate_token
    self.token ||= loop do
      random_token = SecureRandom.urlsafe_base64(nil, false)
      break random_token unless Membership.exists?(token: random_token)
    end
  end

end

app/models/membership_type.rb
class MembershipType < ApplicationRecord
  has_many :memberships
  def pluralize
    unless duration.to_i / 12 < 1.1
      "s"
    end
  end
  def display_name
    "#{name} - #{duration.to_i / 12} year#{pluralize}"
  end

  def display_name_long
    "#{name} Membership - #{duration.to_i / 12} year#{pluralize}"
  end

  def display_name_price_cdn
    "#{name} - #{duration.to_i / 12} year#{pluralize} - #{price / 100}.00 CDN"
  end

  def duration_years
    "#{duration.to_i / 12}"
  end

  def price_cdn
    "#{price / 100}.00 CDN"
  end

  def price_dollar
    "#{price / 100}.00"
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable

end

app/controllers/about_controller.rb
class AboutController < ApplicationController
#  before_filter :redirect_to_https
  def index
  end
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
#  before_filter :redirect_to_https
  before_filter :load_membership
  before_filter :login_from_session!
  before_filter :ensure_authenticated!

def new
  if @membership.nil?
    flash[:error] = "membership not found"
    redirect_to "/"
  end
  @membership_type = @membership.membership_type
end

def index
end

def show
  @charge = @membership.charges.find(params[:id])
end

def create
  # Amount in cents
  @membership_type = @membership.membership_type
  @stripe_token = params[:stripe_token]

  customer = Stripe::Customer.create(
    :email => params[:stripeEmail],
    :source  => params[:stripeToken]
  )

  stripecharge = Stripe::Charge.create(
    :customer    => customer.id,
    :amount      => @membership_type.price,
    :description => "Charge - #{@membership.first_name} #{@membership.last_name}",
    :currency    => 'cad'
  )

  if stripecharge["paid"] == true
    charge = Charge.create({
      membership: @membership,
      membership_type: @membership_type,
      stripe_token: @stripe_token,
      charge_id: stripecharge.id,
      customer_id: customer.id

    })

    if charge.errors.empty?
      redirect_to "/success"
      NewMembershipMailer.welcome_email(@membership).deliver_now
      NewMembershipMailer.welcome_email_admin(@membership).deliver_now
    else
      redirect_to "/memberships/#{@membership.id}/charges/new"
      flash[:error] = "There was a problem creating your account. Please check all fields and try again."
    end
  end


  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to "/memberships/#{@membership.id}/charges/new"
  end
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
#  before_filter :redirect_to_https
  def index
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
#  before_filter :redirect_to_https
  def index
  end
end

app/controllers/letter_controller.rb
class LetterController < ApplicationController
#  before_filter :redirect_to_https
  def index
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/advertising_helper.rb
module AdvertisingHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/letter_helper.rb
module LetterHelper
end

app/helpers/membership_helper.rb
module MembershipHelper
end

app/helpers/resources_helper.rb
module ResourcesHelper
end

app/helpers/success_helper.rb
module SuccessHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
  <head>
    <title>Eagle Moose Lake Property Owners Association | EMLPO</title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <meta name="viewport" content="min-width=device-width, initial-scale=1" />
    <meta name="description" content="" />
    <meta name="HandheldFriendly" content="True" />
    <link rel="icon" type="image/png" href="favicon.png" />
    <link rel="apple-touch-icon" href="apple-touch-iphone.png" />
    <link rel="apple-touch-icon" sizes="72x72" href="apple-touch-ipad.png" />
    <link rel="apple-touch-icon" sizes="114x114" href="apple-touch-iphone4.png" />
    <link rel="apple-touch-icon" sizes="144x144" href="apple-touch-ipad-retina.png" />
    <link rel="sitemap" type="application/xml" title="Sitemap" href="sitemap.xml">
    <link rel="image_src" href="web_img.png" />
    <script src="/deps/jquery-1.9.1.js" type="text/javascript"></script>
    <script src="/deps/jquery-ui.js" type="text/javascript"></script>
    <script src="/deps/bootstrap.js" type="text/javascript"></script>
    <link href="/deps/bootstrap.css" rel="stylesheet" media="screen" />
    <link href="/assets/application.css" rel="stylesheet" media="screen" />
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= csrf_meta_tags %>


  </head>

  <body>
    <nav id="menu" class="menu">
      <div class="mob_menu_head"></div>
      <div class="mob_menu_subhead">Eagle Moose Lake<br>Property Owners Association</div>
      <% if current_user.nil? %>
      <a href="/">
        <div class="mob_menu_line <%= 'active' if current_page?("/") %>">Home</div>
      </a>
      <a href="/about">
        <div class="mob_menu_line <%= 'active' if current_page?("/about") %>">About Us</div>
      </a>
      <a href="/resources">
        <div class="mob_menu_line <%= 'active' if current_page?("/resources") %>">Resources</div>
      </a>
      <a href="/memberships">
        <div class="mob_menu_line <%= 'active' if current_page?("/memberships/new") %>">Membership</div>
      </a>
      <a href="/advertising">
        <div class="mob_menu_line <%= 'active' if current_page?("/advertising") %>">Advertising</div>
      </a>
      <a href="/contact">
        <div class="mob_menu_line <%= 'active' if current_page?("/contact") %>" style="border-bottom:0;">Contact</div>
      </a>
      <% else %>
      <a href="/memberships">
        <div class="mob_menu_line <%= 'active' if current_page?("/memberships") %>">All Memberships</div>
      </a>
      <div class="mob_menu_line"><%= button_to "Logout", "/users/sign_out", method: :delete, class: "mob_logout"  %></div>

      <% end %>
    </nav>
    <main id="panel" class="panel" style="border:0; margin:0; padding:0; border-radius:0;">
      <% if flash[:error] %>
        <div class="flash_shell_error"><%= flash[:error] %></div>
      <% end %>
      <% if flash[:notice] %>
        <div class="flash_shell_notice"><%= flash[:notice] %></div>
      <% end %>
      <div class="container">
        <div class="row">
          <div class="top_shell">
            <button class="btn-hamburger js-slideout-toggle top_nav_mob_btn"></button>
            <% if current_user.nil? %>
            <div class="top_nav_shell">
              <div class="top_nav <%= 'active' if current_page?("/contact") %>"><a href="/contact">Contact</a></div>
              <div class="top_nav <%= 'active' if current_page?("/advertising") %>"><a href="/advertising">Advertising</a></div>
              <div class="top_nav <%= 'active' if current_page?("/memberships/new") %>"><a href="/memberships">Membership</a></div>
              <div class="top_nav <%= 'active' if current_page?("/resources") %>"><a href="/resources">Resources</a></div>
              <div class="top_nav <%= 'active' if current_page?("/about") %>"><a href="/about">About Us</a></div>
              <div class="top_nav <%= 'active' if current_page?("/") %>" style="margin-left:0;"><a href="/">Home</a></div>

            </div>
            <% else %>
              <div class="top_nav_shell">
                <div class="top_nav"><%= button_to "Logout", "/users/sign_out", method: :delete, class: "top_nav_logout"  %></div>

                <div class="top_nav <%= 'active' if current_page?("/memberships") %>"><a href="/memberships">All Memberships</a></div>
                <div class="top_nav"><a href="/memberships"><%= current_user.email %></a></div>
              </div>
            <% end %>

            <div class="top_logo"></div>
            <div class="top_tag">Eagle Moose Lake<br>Property Owners Association</div>
          </div>
        </div>
      </div>

      <%= yield %>
      <div class="bot_outershell">
        <div class="container">
          <div class="row">
            <div class="bot_shell">
              <div class="bot_nav_shell hidden-xs ">
                <div class="bot_nav <%= 'active' if current_page?("/contact") %>"><a href="/contact">Contact</a></div>
                <div class="bot_nav <%= 'active' if current_page?("/advertising") %>"><a href="/advertising">Advertising</a></div>
                <div class="bot_nav <%= 'active' if current_page?("/memberships/new") %>"><a href="/memberships">Membership</a></div>
                <div class="bot_nav <%= 'active' if current_page?("/resources") %>"><a href="/resources">Resources</a></div>
                <div class="bot_nav <%= 'active' if current_page?("/about") %>"><a href="/about">About Us</a></div>
                <div class="bot_nav <%= 'active' if current_page?("/") %>" style="margin-left:0;"><a href="/">Home</a></div>
              </div>
              <div class="bot_logo"></div>
              <div class="bot_tag hidden-sm">Eagle Moose Lake<br>Property Owners Association</div>
              <div class="bot_logo_icon hidden-xs hidden-sm hidden-md"></div>
              <div class="clearfix"></div>
            </div>
          </div>
        </div>
      </div>
    </main>
    <% if @membership.nil? %>
    <% else %>
      <div id="confirm_delete_modal" class="modal fade" tabindex="-1" role="dialog">
        <div class="modal-dialog" role="document">
          <div class="modal-content" style="padding:30px;">
            <div class="modal-header" style="padding-left:0px; padding-right:0px;">
              <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
              <h4 class="modal-title" style="font-family:'roboto_medium', Verdana, Geneva, sans-serif; color:#868686; font-size:24px; line-height:24px;">Delete Membership</h4>
            </div>
            <div class="modal-body" style="padding-left:0px; padding-right:0px; font-family:'roboto_regular', Verdana, Geneva, sans-serif; color:#868686; font-size:15px; line-height:16px;">
              <p>Are you sure you want to delete this membership?</p>
            </div>
            <div class="modal-footer" style="padding:20px 0 0 0;">
              <%= button_to 'Delete Membership', membership_path(@membership, @charges), method: :delete, class: 'mem_form_cancel_confirm_btn' %>
            </div>
          </div><!-- /.modal-content -->
        </div><!-- /.modal-dialog -->
      </div><!-- /.modal -->
    <% end %>
  </body>
  <script src="/deps/slideout.min.js"></script>
  <script type="text/javascript">
    $(document).ready(function () {
      var slideout = new Slideout({
        'panel': document.getElementById('panel'),
        'menu': document.getElementById('menu'),
        'side': 'left'
      });

      document.querySelector('.js-slideout-toggle').addEventListener('click', function() {
        slideout.toggle();
      });

      document.querySelector('.menu').addEventListener('click', function(eve) {
        if (eve.target.nodeName === 'A') { slideout.close(); }
      });
    });
  </script>
</html>

app/views/layouts/charges.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
  <head>
    <title>Eagle Moose Lake Property Owners Association | EMLPO</title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <meta name="viewport" content="min-width=device-width, initial-scale=1" />
    <meta name="description" content="" />
    <meta name="HandheldFriendly" content="True" />
    <link rel="icon" type="image/png" href="favicon.png" />
    <link rel="apple-touch-icon" href="apple-touch-iphone.png" />
    <link rel="apple-touch-icon" sizes="72x72" href="apple-touch-ipad.png" />
    <link rel="apple-touch-icon" sizes="114x114" href="apple-touch-iphone4.png" />
    <link rel="apple-touch-icon" sizes="144x144" href="apple-touch-ipad-retina.png" />
    <link rel="sitemap" type="application/xml" title="Sitemap" href="sitemap.xml">
    <link rel="image_src" href="web_img.png" />
    <script src="/deps/jquery-1.9.1.js" type="text/javascript"></script>
    <script src="/deps/jquery-ui.js" type="text/javascript"></script>
    <script src="/deps/bootstrap.js" type="text/javascript"></script>
    <link href="/deps/bootstrap.css" rel="stylesheet" media="screen" />
    <link href="/assets/application.css" rel="stylesheet" media="screen" />
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <nav id="menu" class="menu">
      <div class="mob_menu_head"></div>
      <div class="mob_menu_subhead">Eagle Moose Lake<br>Property Owners Association</div>
      <% if current_user.nil? %>
      <a href="/">
        <div class="mob_menu_line <%= 'active' if current_page?("/") %>">Home</div>
      </a>
      <a href="/about">
        <div class="mob_menu_line <%= 'active' if current_page?("/about") %>">About Us</div>
      </a>
      <a href="/resources">
        <div class="mob_menu_line <%= 'active' if current_page?("/resources") %>">Resources</div>
      </a>
      <a href="/memberships">
        <div class="mob_menu_line <%= 'active' if current_page?("/memberships/new") %>">Membership</div>
      </a>
      <a href="/advertising">
        <div class="mob_menu_line <%= 'active' if current_page?("/advertising") %>">Advertising</div>
      </a>
      <a href="/contact">
        <div class="mob_menu_line <%= 'active' if current_page?("/contact") %>" style="border-bottom:0;">Contact</div>
      </a>
      <% else %>
      <a href="/memberships">
        <div class="mob_menu_line <%= 'active' if current_page?("/memberships") %>">All Memberships</div>
      </a>
      <div class="mob_menu_line"><%= button_to "Logout", "/users/sign_out", method: :delete, class: "mob_logout"  %></div>

      <% end %>
    </nav>
    <main id="panel" class="panel" style="border:0; margin:0; padding:0; border-radius:0;">
      <% if flash[:error] %>
        <div class="flash_shell_error"><%= flash[:error] %></div>
      <% end %>
      <% if flash[:notice] %>
        <div class="flash_shell_notice"><%= flash[:notice] %></div>
      <% end %>
      <div class="container">
        <div class="row">
          <div class="top_shell">
            <button class="btn-hamburger js-slideout-toggle top_nav_mob_btn"></button>
            <% if current_user.nil? %>
            <div class="top_nav_shell">
              <div class="top_nav <%= 'active' if current_page?("/contact") %>"><a href="/contact">Contact</a></div>
              <div class="top_nav <%= 'active' if current_page?("/advertising") %>"><a href="/advertising">Advertising</a></div>
              <div class="top_nav <%= 'active' if current_page?("/memberships/new") %>"><a href="/memberships">Membership</a></div>
              <div class="top_nav <%= 'active' if current_page?("/resources") %>"><a href="/resources">Resources</a></div>
              <div class="top_nav <%= 'active' if current_page?("/about") %>"><a href="/about">About Us</a></div>
              <div class="top_nav <%= 'active' if current_page?("/") %>" style="margin-left:0;"><a href="/">Home</a></div>

            </div>
            <% else %>
              <div class="top_nav_shell">
                <div class="top_nav"><%= button_to "Logout", "/users/sign_out", method: :delete, class: "top_nav_logout"  %></div>

                <div class="top_nav <%= 'active' if current_page?("/memberships") %>"><a href="/memberships">All Memberships</a></div>
                <div class="top_nav"><a href="/memberships"><%= current_user.email %></a></div>
              </div>
            <% end %>

            <div class="top_logo"></div>
            <div class="top_tag">Eagle Moose Lake<br>Property Owners Association</div>
          </div>
        </div>
      </div>

      <%= yield %>
      <div class="bot_outershell">
        <div class="container">
          <div class="row">
            <div class="bot_shell">
              <div class="bot_nav_shell hidden-xs ">
                <div class="bot_nav <%= 'active' if current_page?("/contact") %>"><a href="/contact">Contact</a></div>
                <div class="bot_nav <%= 'active' if current_page?("/advertising") %>"><a href="/advertising">Advertising</a></div>
                <div class="bot_nav <%= 'active' if current_page?("/memberships/new") %>"><a href="/memberships">Membership</a></div>
                <div class="bot_nav <%= 'active' if current_page?("/resources") %>"><a href="/resources">Resources</a></div>
                <div class="bot_nav <%= 'active' if current_page?("/about") %>"><a href="/about">About Us</a></div>
                <div class="bot_nav <%= 'active' if current_page?("/") %>" style="margin-left:0;"><a href="/">Home</a></div>
              </div>
              <div class="bot_logo"></div>
              <div class="bot_tag hidden-sm">Eagle Moose Lake<br>Property Owners Association</div>
              <div class="bot_logo_icon hidden-xs hidden-sm hidden-md"></div>
              <div class="clearfix"></div>
            </div>
          </div>
        </div>
      </div>
    </main>
  </body>
  <script src="/deps/slideout.min.js"></script>
  <script type="text/javascript">
    $(document).ready(function () {
      var slideout = new Slideout({
        'panel': document.getElementById('panel'),
        'menu': document.getElementById('menu'),
        'side': 'left'
      });

      document.querySelector('.js-slideout-toggle').addEventListener('click', function() {
        slideout.toggle();
      });

      document.querySelector('.menu').addEventListener('click', function(eve) {
        if (eve.target.nodeName === 'A') { slideout.close(); }
      });
    });
  </script>
</html>

app/views/resources/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-12 col-lg-12 no_pad" style="border-left:1px solid #e6e6e6; border-right:0px solid #e6e6e6;">
      <div class="section_top_img">
        <img src="/assets/res_top_img.jpg" class="img-responsive">
      </div>
    </div>
  </div>
</div>

<div class="container container_style">
  <div class="row" style="margin-top:40px;">
    <div class="col-sm-4 col-md-4 col-lg-4 no_pad">
      <div class="res_col">
        <div class="res_col_img col1"></div>
        <div class="res_col_head">Coalition of Haliburton <br class="hidden-sm hidden-xs">Property Owners Assoc.</div>
        <a href="http://www.cohpoa.org/" target="_blank"><div class="res_col_btn">View website</div></a>
      </div>
    </div>
    <div class="col-sm-4 col-md-4 col-lg-4 no_pad">
      <div class="res_col">
        <div class="res_col_img col2"></div>
        <div class="res_col_head">Healthy Shorelines <br class="hidden-sm hidden-xs">for Healthy Lakes</div>
        <a href="http://www.loveyourlake.ca" target="_blank"><div class="res_col_btn">View website</div></a>
      </div>
    </div>
    <div class="col-sm-4 col-md-4 col-lg-4 no_pad">
      <div class="res_col">
        <div class="res_col_img col3"></div>
        <div class="res_col_head">Coalition For Equitable <br class="hidden-sm hidden-xs">Water Flow</div>
        <a href="http://cewf.typepad.com/coalition_for_equitable_w/" target="_blank"><div class="res_col_btn">View website</div></a>
      </div>
    </div>
  </div>
  <div class="row" style="margin-top:-5px; border-top:1px dashed #e6e6e6; margin-bottom:-20px; width:100%;"></div>
  <div class="row" style="margin-top:40px;">
    <div class="col-sm-4 col-md-4 col-lg-4 no_pad">
      <div class="res_col">
        <div class="res_col_img col4"></div>
        <div class="res_col_head">Safe Boating Guide</div>
        <a href="http://www.tc.gc.ca/eng/marinesafety/debs-obs-menu-1362.htm" target="_blank"><div class="res_col_btn">View website</div></a>
      </div>
    </div>
    <div class="col-sm-4 col-md-4 col-lg-4 no_pad">
      <div class="res_col">
        <div class="res_col_img col5"></div>
        <div class="res_col_head">Municipality of Dysart et al.</div>
        <a href="http://www.dysartetal.ca/" target="_blank"><div class="res_col_btn">View website</div></a>
      </div>
    </div>
    <div class="col-sm-4 col-md-4 col-lg-4 no_pad">

    </div>
  </div>
</div>
<div class="bot_tag_shell">
  <div class="container">
    <div class="row">
      <div class="col-sm-12 col-md-12 col-lg-12 no_pad">
        <div class="bot_tag_head">To receive the benefits <br class="visible-xs">of an EMLPO <br class="hidden-xs">membership, <br class="visible-xs"><span>sign up today!</span></div>
        <a href="/memberships"><div class="bot_tag_btn">Click here to sign up</div></a>
      </div>
    </div>
  </div>
</div>